First neuron

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Single neuron

In [2]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0] * weights[0] + 
          inputs[1] * weights[1] + 
          inputs[2] * weights[2] + bias)

print(output)

2.3


Using numpy

In [9]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2

outputs = np.dot(inputs, weights) + bias
print(outputs)

2.3


Layers of neurons

In [3]:
inputs = [1,2,3,2.5]
weights1 = [0.2, 0.8, -0.5, 1] 
weights2 = [0.5, -0.91, 0.26, -0.5] 
weights3 = [-0.26, -0.27, 0.17, 0.87] 
 
bias1 = 2 
bias2 = 3 
bias3 = 0.5 
 
outputs = [ 
        # Neuron 1: 
        inputs[0]*weights1[0] + 
        inputs[1]*weights1[1] + 
        inputs[2]*weights1[2] + 
        inputs[3]*weights1[3] + bias1, 
 
        # Neuron 2: 
        inputs[0]*weights2[0] + 
        inputs[1]*weights2[1] + 
        inputs[2]*weights2[2] + 
        inputs[3]*weights2[3] + bias2, 
 
        # Neuron 3: 
        inputs[0]*weights3[0] + 
        inputs[1]*weights3[1] + 
        inputs[2]*weights3[2] + 
        inputs[3]*weights3[3] + bias3] 
 
print(outputs) 

[4.8, 1.21, 2.385]


With numpy

In [9]:
inputs = [1,2,3,2.5]
weights = np.array([[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]])
bias = np.array([2, 3, 0.5])

output_layers = np.dot(weights, inputs) + bias


print(output_layers)

print(weights.shape)
print(len(inputs))

[4.8   1.21  2.385]
(3, 4)
4


Layers with batches of data

In [7]:
inputs = np.array([[1,2,3,2.5], 
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8]])
weights = np.array([[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]).T

bias = np.array([2, 3, 0.5])
outputs = np.dot(inputs, weights) + bias

print(outputs)
print(weights.shape)
print(inputs.shape)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
(4, 3)
(3, 4)


In [29]:
import numpy as np

a = np.array([[1,4],[2,5],[3,6]])
b = np.array(([1,.5,.7],[.2,.3,.4]))
bias = np.array([1,2,3])
c = np.dot(a,b) + bias

print(a)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
d = np.array([[.7,.5],[.6,.4],[.8,.7]])
bias2 = np.array([1,.3])

l2 = np.dot(c,d) + bias2
l2

array([[ 9.42,  6.89],
       [11.62,  8.58],
       [13.82, 10.27]])

In [27]:
exp_values = np.exp(l2 - np.max(l2, axis= 1, keepdims=True))
        
probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
        

print(probabilities)

[[0.92621835 0.07378165]
 [0.95434883 0.04565117]
 [0.97207743 0.02792257]]


0.07427357821433388
